version: "3.8"
services:
  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
